# Generated by Django 5.1.5 on 2025-03-27 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('historico', 'Histórico'), ('esportivo', 'Esportivo'), ('culinario', 'Culinário'), ('cultural', 'Cultural'), ('natural', 'Natural')], default='historico', help_text='Classificação do tipo de local.', max_length=20, verbose_name='Categoria')),
                ('habilitado', models.BooleanField(default=True, help_text='Define se o local estará visível no front-end.', verbose_name='Habilitado')),
                ('nome', models.CharField(help_text='Nome do local.', max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(help_text='Breve descrição sobre o local.', verbose_name='Descrição')),
                ('link', models.URLField(blank=True, help_text='Link para o site oficial ou página no Wikipedia.', max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Link')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem representativa do local.', null=True, upload_to='locais/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'ordering': ['nome'],
            },
        ),
    ]
